### ISSUE TITLE
Logic-1 Access to client

### ISSUE THREAD

**Issue by alvarovalderramamolina** [alvarovalderramamolina/SGPM#34]
### Description
Implements access in the application like a client

### Tasks

- [x] Collects the data entered in the form
- [x] Checks the DataModel with access data 
- [x] Change the activity with intent like the example the down
`Intent intent = new Intent (v.getContext(), YourClass.class);`
`startActivity(intent)`
